### ISSUE TITLE
Docker Build Addition (Completed)

### ISSUE THREAD

**Issue by nathanhicks** [ProjectEQ/peqphpeditor#16]
I wrote a docker build of this awesome editor and a PEQ database container at https://github.com/nathanhicks/docker-peqphpeditor and was wondering if there was any interest in adding that to this repository or linking to it somehow?  Thanks and I appreciate you posting this app!

**Comment by Akkadius** [comment]
Hey Nate! Thanks for submitting this, when I get some time I will pull this down and review before looking at putting it on the repo
