### ISSUE TITLE
update_spell Fix with php7.2

### ISSUE THREAD

**Issue by moguay** [ProjectEQ/peqphpeditor#25]
To Fix 502 Bad Gateway return, need to update_spell() with php 7.2

line 251 in spells.php:
    if($vars[$f] != stripslashes($_POST[$f]) and isset($_POST[$f])) { $fields .= "`$f` = \"$_POST[$f]\", "; }
to
    if (isset($_POST[$f])) {
        if($vars[$f] != stripslashes($_POST[$f])) { $fields .= "`$f` = \"$_POST[$f]\", "; }
    }

**Comment by joligario** [comment]
Is this unique to 7.2? I get no issues with 7.3.

Instead, try replacing "and" with "&&"?

**Comment by joligario** [comment]
And maybe flip/flop the isset check
