### ISSUE TITLE
NPC Special Abilities always updated

### ISSUE THREAD

**Issue by moguay** [ProjectEQ/peqphpeditor#27]
Hi, we have get some bad write on npc Special Abilities, so i have investigate and see all the time is rewrite.
Is just a problem on the last ^ separator need to be removed
just adding this line to check and remove it: if(SUBSTR($new_specialattks, -1) == '^'){$new_specialattks = SUBSTR($new_specialattks, 0, -1);}

Line 1282 npc.php file
// Check for special attacks change
$new_specialattks = '';
$flag = 0;
foreach ($specialattacks as $k=>$v) {
  if (isset($_POST["$k"])) {
    if(SUBSTR($_POST["$k"], -1) != '^' && $_POST["$k"] != ''){$_POST["$k"].= '^';}
    $new_specialattks .= $_POST["$k"];
  }
}
++ if(SUBSTR($new_specialattks, -1) == '^'){$new_specialattks = SUBSTR($new_specialattks, 0, -1);}

if ($special_abilities != $new_specialattks) {
  $flag = 1;
}

I dont know where is from my background problem on badly rewrite. Gm see sometime white screen on save npc editor and also Internal error when specialattks is corrupted.
The only why is fix manually in the DB

**Comment by joligario** [comment]
Check line 1422:
$query2 = "UPDATE npc_types SET special_abilities = TRIM(TRAILING '^' FROM special_abilities)";
