### ISSUE TITLE
Your database schema (9164) does not match the current binary database version (9163)

### ISSUE THREAD

**Issue by joedit-cmd** [ProjectEQ/peqphpeditor#29]
Hi, I did a fresh installation of eqemulator on ubuntu, and installed PEQ Editor. Everything seems to work fine including the PEQ Editor, however, I received this error when I login to PEQ: "Your database schema (9164) does not match the current binary database version (9163). You may experience errors or inaccurate data if you continue."

Does anyone know how I can fix this error? Thanks.

![PEQ error](https://user-images.githubusercontent.com/59481836/116928392-0016d680-ac2b-11eb-803a-ed7e5edb5be9.jpg)

**Comment by joligario** [comment]
There is nothing to do right now. This just means you have updated the character experience modifiers and the editor doesn't yet support them. https://github.com/EQEmu/Server/blob/master/utils/sql/git/required/2021_04_23_character_exp_modifiers.sql

This particular difference won't affect the operation of the editor.
